version: "3.9"

services:
  glue_jupyter_lab:
    image: amazon/aws-glue-libs:glue_libs_4.0.0_image_01
    container_name: glue_jupyter_lab
    command: ["/home/glue_user/jupyter/jupyter_start.sh"]
    volumes:
      - aws_credentials:/home/glue_user/.aws:ro
      - ${PWD}/scripts:/home/glue_user/workspace/scripts
      - ${PWD}/jupyter_workspace:/home/glue_user/workspace/jupyter_workspace
    environment:
      - AWS_PROFILE=${PROFILE_NAME}
      - DISABLE_SSL=${DISABLE_SSL}
    ports:
      - "4040:4040"
      - "18080:18080"
      - "8998:8998"
      - "8888:8888"
    stdin_open: true
    tty: true
    restart: unless-stopped
volumes:
  aws_credentials:
