version: "3.9"

services:
  glue_pyspark:
    image: amazon/aws-glue-libs:glue_libs_4.0.0_image_01
    container_name: glue_pyspark
    entrypoint: /home/glue_user/spark/bin/pyspark
    volumes:
      - ~/.aws:/home/glue_user/.aws:ro
      - ${PWD}/scripts:/home/glue_user/workspace/scripts
    environment:
      - AWS_PROFILE=${PROFILE_NAME}
      - DISABLE_SSL=${DISABLE_SSL}
    ports:
      - "4040:4040"
      - "18080:18080"
      - "5678:5678"
    stdin_open: true
    tty: true
    restart: unless-stopped
